services:
  octopus:
    image: ghcr.io/1229984599/octopus
    ports:
       - '8080:8080'
    extra_hosts:
       - 'host.docker.internal:host-gateway'
    volumes:      
       - '/path/to/data:/app/data'
    container_name: octopus
    restart: unless-stopped
